### ISSUE TITLE
Error with command : npm install

### ISSUE THREAD

**Issue by mohamedmehdigara** [adriandelgg/beginner-web3-todolist#1]
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network In most cases you are behind a proxy or have bad network settings.      
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-01-27T16_57_58_809Z-debug.log

**Comment by adriandelgg** [comment]
Hi, this is an extremely old project I haven't touched on in months.

However, I had done one similar to it recently that is new and works. 

Here's a link: https://github.com/adriandelgg/eth-todo-list
